### PR TITLE
Improve gecko gdb support

### PR DESCRIPTION
**Pull request by asutherland**
Without these changes, when run against a mozilla-central (gecko) source tree, no gdb files will be found.

With these changes, the gdbs will be found and an attempt made to load them, but the `import gdbpp` line will fail on `gdb.lookup_type("uintptr_t")` because the .gdbinit will be loaded before such a symbol is known.

Gecko users can work-around this issue by typing `python import gdbpp` later on and then everything will be fine.  Or that problem could be fixed, but arguably this is an improvement.

Because it seems like ".gdbinit" might have inadvertantly become load bearing even though the comment said it was for "mozilla", I've left it in.

### CODE REVIEW

**Comment by khuey** [comment]
Hrm, perhaps we should reorder the loading sequence in Pernosco to handle gdbinit later. Not sure if that'll break anything.

**Comment by asutherland** [comment]
It turns out I was wrong about what was throwing; it's actually the JS pretty printers in [prettyprinters.py](https://searchfox.org/mozilla-central/rev/b5b551329484a67f2abb4bae50411b93d5851733/js/src/gdb/mozilla/prettyprinters.py#217).

If it's possible to wait until later, that would probably be helpful.  Based on my very superficial reading of the gdb docs it didn't seem like there was necessarily a way to be like "go back in time and load the stuff you didn't load when you could have".

I think in general this probably isn't a problem for normal gdb usage for Firefox because https://searchfox.org/mozilla-central/source/toolkit/library/libxul.so-gdb.py is inherently only loaded after libxul.  But the logic in there won't work on pernosco because that "/build/.gdbinit" file won't exist, and even if it did exist, the paths that end up in there come from https://searchfox.org/mozilla-central/source/build/.gdbinit.py.in which is hard-coding our "topsrcdir".  I also think that mechanism may also have issues because gdb is saying pernosco saved off the libxul using the path objdir/dist/lixbxul.so but that's a symlink, so it doesn't realize the real path is objdir/toolkit/library/build/libxul.so

Now that I better understand what pernosco-submit is doing and the resulting path structure it uses, I can probably work up changes to mozilla-central that make libxul.so-gdb.py work instead of adding a custom init.

**Comment by khuey** [comment]
> Hrm, perhaps we should reorder the loading sequence in Pernosco to handle gdbinit later. Not sure if that'll break anything.

Alright I've made this change in production.

**Comment by khuey** [comment]
@asutherland are you still working on this or should I take a look at it?

**Comment by asutherland** [comment]
> > Hrm, perhaps we should reorder the loading sequence in Pernosco to handle gdbinit later. Not sure if that'll break anything.
> 
> Alright I've made this change in production.

This works great.  When you made this change, my existing trace was not instantaneously happy, but then I guess it expired and when it got rebuilt it had your new changes?  I also did a fresh submit of the the exact same trace using the changes of this PR and it was also happy out of the gate.

I likely won't have additional cycles in this space for a while, so please do feel free to iterate/change anything in the PR you don't like.

**Comment by khuey** [comment]
> I guess it expired and when it got rebuilt it had your new changes?

Yeah that's right.

**Comment by asutherland** [comment]
I'm adding another pretty printer to Gecko I think, so I just remembered this and thought I'd ping.  Specifically, I think as I left this, it works for me, and it would probably be nice if it could land for other Gecko hackers as long as there's no breakage for your other users/customers/etc.

**Comment by khuey** [comment]
Sure, just forgot about this, thanks.

**Comment by asutherland** [comment]
Thank you!

**Pull request merged**
